### ISSUE TITLE
素数判定

### ISSUE THREAD

**Issue by takaemonn** [c0b21027/ProjExD#4]
https://github.com/c0b21027/ProjExD/blob/39aeeff29a2b8f33dce46826dd9a9776e6edc8bb/ex02/calc.py#L51
https://qiita.com/srtk86/items/874639e361917e5016d4 を参考にエラトステネスの篩以外の方法で実行できると思います。

**Comment by c0b21027** [comment]
普通の素数判定も考えましたが、Ο(n log log n)であるためこちらのほうが速いと感じた所存です。
