### ISSUE TITLE
座標の表現

### ISSUE THREAD

**Issue by takaemonn** [c0b21027/ProjExD#6]
https://github.com/c0b21027/ProjExD/blob/72d5332717f6fa961173e3c22d7769d1a0694912/ex03/maze.py#L57
13＊100＋50ではなく、1350で表したほうがいいと思う。この下の行も同様

**Comment by c0b21027** [comment]
ご指摘ありがとうございます。未だに座標が定まっておらず、ゴールへ移動する方向によって結果が変わってしまうのですぐに変更できるようにこのようなコードにしました。
